apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-public-key
data:
  public_key.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuLRxVdaPbGRXPHZ+5f0l
    7l7I9hDI480gRp5RQ1ZWWfAvdqqxZHfb1ZkqahbUlC2FG5v203RqIBEK5Oo5zFpn
    DiaSTHO3Mm94TWXk1NqnddUy34C+rD54P7WBjH8a9Q4mGJjEY1bOLALVcKLdov0e
    5P3GSY7527POVGWa+mzWQYe3xCBJk2pWtG3irA0RVJP2J74nBn+tt0YuCv6hOYYj
    YAPvfKq0VbfZ0Ij0Ih7puwXwUHO4vWJ7UYYab/VlGxhg2FhQ8Zx9VtckJxc2g3/u
    wOnKkdM6UXn8jXvEm+VY79fPLSlpHKMDvDAQh7TXXmT4SKlHEaUQs72xfzBOawoD
    0QIDAQAB
    -----END PUBLIC KEY-----
