apiVersion: v1
kind: Service
metadata:
  name: shop
  labels:
    app: shop
    service: shop
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app: shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - image: docker.io/tinsae/shop-demo:2.0.0
          imagePullPolicy: IfNotPresent
          name: shop
          ports:
            - containerPort: 3000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shop
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /shop
      route:
        - destination:
            host: shop
            port:
              number: 3000
