apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
    service: user
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: user

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      volumes:
        - name: private-key
          secret:
            secretName: jwt-private-key
      containers:
        - name: user
          image: docker.io/tinsae/user-demo:6.2.6
          volumeMounts:
            - name: private-key
              mountPath: /etc/jwt
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /api/user
      route:
        - destination:
            host: user
            port:
              number: 3000
