apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deploy
  labels:
    app: shopping-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart-service
          image: docker.io/romeomugwa/shoppingcart-service:1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-shopping-cart-deploy
                  key: mysql-root-password
            - name: MYSQL_HOST
              value: mysql-shopping-cart-deploy.default.svc.cluster.local
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: shopping_cart_db
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
  labels:
    app: shopping-cart
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: shopping-cart
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shopping-cart-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /carts
      route:
        - destination:
            host: shopping-cart
            port:
              number: 80
